Giancarlo Flores

Hello, my name is Giancarlo! I'm from Piscataway, NJ and I went to Piscataway High School.
My hobbies are listening to music, dancing, working out, watching anime, playing videogames, and sleeping too.
I'm hispanic, being half-guatemalan and half-salvadoran. I also was in my high school's marching band and I've played trombone for 8 years.
I can be pretty quiet and introverted at first, but once I get comfortable, I enjoy talking with people, making friends, and being someone others can rely on.
One of my biggest goals is to become a successful software engineer, build a stable future for myself, and eventually be able to support the people I care about.

